### ISSUE TITLE
updateLinkedToService requires redeploy

### ISSUE THREAD

**Issue by justinkelly** [allansun/docker-cloud-php-api#2]
Hi Allan,

Awesome work on this!!!!!

I've updated my code to use your master branch and all is working great, 

it just seems that when using updateLinkedToService ( https://github.com/allansun/docker-cloud-php-api/blob/master/src/API/Service.php#L215 ) that the links in that service do get updated but are not activated until a redeploy

I'm using `updateLinkedToService` to update the load balancer service to newly created web services

```
//set load balancers links
$DockerCloud_LoadBalancer->setLinkedToService($link);

//do update - no redeploy?
DockerCloud_Service_API = new DockerCloud\API\Service();
$DockerCloud_Service_API->updateLinkedToService($DockerCloud_LoadBalancer);
```

note: am using the tutum/haproxy image for the load balancer

quite possible I'm doing somethign wrong - but if you have any thoughts/info on this it would be greatly appreciated!!!!!!!!!!

Cheers

Justin

**Comment by justinkelly** [comment]
update: just udpated the haproxy to dockercloud/haproxy instead of tutum/haproxy and this may be resolved

will do more testing and update this issues

thanks again!!!

**Comment by allansun** [comment]
Hi Justin,

There must be some weird settings in my Gmail I didn't get the notification .... sorry about the late reply.

I'm very glad this lib actually helped people

Yes you are in the right direction. the tutum/haproxy and dockercloud/haproxy problem puzzled me quite a while and I fixed it exactly like what you have done. 

What caused that not working as expected was because in the HAProxy image, they expected some environment variables like DOCKERCLOUD_\* in order to get HAProxy update script correctly detect newly linked service, where tutum/haproxy was looking for TUTUM_*.

@sonytwo (twitter) is the one developed tutum/haproxy and dockercloud/haproxy you can contact him for any questions regarding haproxy image

**Comment by allansun** [comment]
Ha! Just found it in my Gmail’s ‘Forums’ category, which is now shown in
the inbox!

Filtered out these emails hopefully I will see notifications in the future!

Best regards,
Allan Sun

**Comment by justinkelly** [comment]
thanks @allansun !!! this project has been a HUGE help to me!

1 question: will you be tagging the master/dev branch soon - had some issue with composer trying to get the latest code

cheers

justin

**Comment by allansun** [comment]
@justinkelly I've just tagged the latest commit to be version 1.4, which you will be able to retrieve from @stable tag. I wasn't sure if that last commit was satisfactory enough to be 1.4 so it wasn't tagged, and as you know, once you are satisfied with your code, you forgot to maintain it ... :laughing: 

{
    "require-dev": {
        "dockercloud/api": "@stable"
    }
}

**Comment by justinkelly** [comment]
thanks allan!!!!! keep up the awesome work
