### ISSUE TITLE
Use a different client for web socket (WSS) requests

### ISSUE THREAD

**Issue by jpcaparas** [allansun/docker-cloud-php-api#7]
Unfortunately, some commands don't work (i.e. [executing a command inside a container](https://docs.docker.com/apidocs/docker-cloud/#execute-command-inside-a-container) do not work) because the [Guzzle HTTP client doesn't support web sockets](https://github.com/guzzle/guzzle/issues/1719).

I am getting this error:

```
cURL error 1: Protocol "wss" not supported or disabled in libcurl (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

... when I issue this command:

```php
$api->exec($container->getUuid(), 'php -v',
    function (GuzzleHttp\Psr7\Response $response) {
        print_r($response);
    },
    function (GuzzleHttp\Exception\RequestException $e) {
        print_r($e->getMessage());
    });
```

Can we use a different client for web sockets?

**Comment by allansun** [comment]
@jpcaparas you are correct indeed that Guzzle doesn't support web socket protocol.

That's why I used [WebSocket](https://github.com/allansun/websocket-php) (A fork from https://github.com/Textalk/websocket-php but with my twist to make it working with docker cloud).

Look at https://github.com/allansun/docker-cloud-php-api/blob/master/src/Client.php#L82 you will see it uses the WebSocket lib.

Instead of passing closure you can also try to just pass 'TRUE' to the third and fourth parameters, this will use the default Logger to log info. 

We use the this lib on daily basis in our CD practice  , this WSS request is used every time when we do a deploy and we use [Phinx](https://phinx.org/) to update the database schema. So I am pretty sure it works.

Come back to me if you still have problem.

**Comment by jpcaparas** [comment]
@allansun 

Hi man sorry for getting back to you late on this. I appreciate all the work you've put into this.

I think I was using an outdated commit. 

> Instead of passing closure you can also try to just pass 'TRUE' to the third and fourth parameters, this will use the default Logger to log info.

Yep, that's what I did. It's just weird that the _WSS request wasn't returning a value_. Can this be something you could look into?

> We use the this lib on daily basis in our CD practice , this WSS request is used every time when we do a deploy and we use Phinx to update the database schema. So I am pretty sure it works.

I'm really keen to know good deployment practices for Docker-Compose powered applications. What good resources would you recommend. Thanks.

**Comment by allansun** [comment]
Hi @jpcaparas 

Sorry due to the unpopularity (unfortunately😭) of this project, I didn't maintain the version up-to-date. Just pushed the latest commit as v1.8, you should be safe to use @stable version tag now. (I'm using dev-master).

> Instead of passing closure you can also try to just pass 'TRUE' to the third and fourth parameters, this will use the default Logger to log info.
>> Yep, that's what I did. It's just weird that the WSS request wasn't returning a value. Can this be something you could look into?

I cannot reproduce the problem. Have to tried to debug and see what the values passed to the break point?

> We use the this lib on daily basis in our CD practice , this WSS request is used every time when we do a deploy and we use Phinx to update the database schema. So I am pretty sure it works.
>> I'm really keen to know good deployment practices for Docker-Compose powered applications. What good resources would you recommend. Thanks.

Even though DockerCloud advertise itself as the 'Stackfile' can be very much a drop-in replace for the 'DockerCompose' file, I found it quite hard to use DockerCompose for productions use. That's why I created this lib so all values can be generated on the fly. 

After using DockerCloud for almost 2 years, I found it good for simple projects however as our project grows there are quite a lot of areas DockerCloud cannot cover for real life production environment. Hence we are turning into Kubernetes at the moment. I have also recently created a PHP client to fully support Kubernetes version 1.6 ( https://github.com/allansun/kubernetes-php-client ). It's not fully tested yet and have not put into production use yet, but that's my goal for the coming two weeks.

However, if you a still trying to choose a docker orchestra solution, I would still recommend to you start with DockerCloud first, as the learning curve of Kubernetes is quite high...

In regards to resources I am sorry I don't have much ...
